services:
  backend:
    image: 681447158789.dkr.ecr.ap-south-2.amazonaws.com/hiring-ai-backend-staging:8f894f2
    pull_policy: never
    container_name: hiring_backend_staging
    restart: always
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=staging
      - AWS_REGION=ap-south-2
      - DATABASE_URL=postgresql+asyncpg://psqladmin:StagingSecurePass123!@psql-hiring-staging.cfsu662ea62k.ap-south-2.rds.amazonaws.com:5432/hiring_db
      - S3_BUCKET_NAME=sthiring-documents-staging-ap-south-2
      - SQS_QUEUE_URL=https://sqs.ap-south-2.amazonaws.com/681447158789/staging-application-events
      - SECRET_KEY=staging-super-secret-key-32chars-min!!
      - ENCRYPTION_KEY=d3RhZ2luZy1zZWNyZXQtZW5jcnlwdGlvbi1rZXkxMjM=
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health/liveness"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  frontend:
    image: 681447158789.dkr.ecr.ap-south-2.amazonaws.com/hiring-ai-frontend-staging:8f894f2
    pull_policy: never
    container_name: hiring_frontend_staging
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://16.112.131.122:8000
    depends_on:
      backend:
        condition: service_healthy

  worker:
    image: 681447158789.dkr.ecr.ap-south-2.amazonaws.com/hiring-ai-worker-staging:8f894f2
    pull_policy: never
    container_name: hiring_worker_staging
    restart: always
    command: ["python", "-m", "app.worker"]
    environment:
      - ENVIRONMENT=staging
      - AWS_REGION=ap-south-2
      - DATABASE_URL=postgresql+asyncpg://psqladmin:StagingSecurePass123!@psql-hiring-staging.cfsu662ea62k.ap-south-2.rds.amazonaws.com:5432/hiring_db
      - S3_BUCKET_NAME=sthiring-documents-staging-ap-south-2
      - SQS_QUEUE_URL=https://sqs.ap-south-2.amazonaws.com/681447158789/staging-application-events
      - SECRET_KEY=staging-super-secret-key-32chars-min!!
      - ENCRYPTION_KEY=d3RhZ2luZy1zZWNyZXQtZW5jcnlwdGlvbi1rZXkxMjM=
    depends_on:
      backend:
        condition: service_healthy
