"use client";
import Link from "next/link";
import { ArrowRight, BriefcaseBusiness, Check, ChevronRight, MapPin, Sparkles, TrendingUp } from "lucide-react";
import { useAuth } from "@/components/auth/AuthContext";

const recommendations=[
 {id:"ai-ml-engineer",title:"AI/ML Engineer",company:"Aster Labs",location:"Bengaluru · Hybrid",match:94,salary:"₹18L – ₹26L",skills:["Python","Machine Learning","FastAPI","SQL"],gap:"Kubernetes",tone:"bg-violet-100 text-violet-700"},
 {id:"applied-ai",title:"Applied AI Engineer",company:"Northstar Health",location:"Remote · India",match:91,salary:"₹20L – ₹30L",skills:["LLMs","RAG","Python","Docker"],gap:"AWS",tone:"bg-sky-100 text-sky-700"},
];
const trends=["Applied AI Engineer","Machine Learning Engineer","AI Product Specialist"];
export default function CandidateDashboardPage(){ const {user}=useAuth(); const name=user?.full_name?.split(" ")[0]||"Gnanendhra"; return <div className="h-page space-y-6">
 <section className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="page-eyebrow">Career home</p><h1 className="page-title">Good evening, {name} <span className="text-base">👋</span></h1><p className="page-subtitle">Your AI career assistant found new opportunities for you.</p></div><Link href="/jobs" className="h-btn h-btn-secondary">Browse all jobs <ArrowRight size={16}/></Link></section>
 <section className="h-card ai-card p-5 sm:p-6 relative overflow-hidden"><div className="absolute -right-12 -top-12 h-40 w-40 rounded-full bg-violet-300/20 blur-2xl"/><div className="relative flex flex-col gap-5 md:flex-row md:items-center"><div className="grid h-11 w-11 place-items-center rounded-xl bg-violet-600 text-white"><Sparkles size={21}/></div><div className="flex-1"><div className="flex items-center gap-2"><span className="h-chip bg-white text-violet-700">AI recommendations</span><span className="text-xs text-slate-500">Updated just now</span></div><h2 className="mt-2 text-xl font-bold text-slate-900">12 new opportunities match your profile</h2><p className="mt-1 text-sm text-slate-600">We ranked roles by your skills, experience and career direction—not just keywords.</p></div><div className="flex gap-5 text-sm"><div><strong className="block text-lg text-slate-900">8</strong><span className="text-slate-500">Excellent</span></div><div><strong className="block text-lg text-slate-900">4</strong><span className="text-slate-500">Good match</span></div></div><Link href="/jobs" className="h-btn">View recommendations <ArrowRight size={16}/></Link></div></section>
 <div className="grid gap-6 xl:grid-cols-[245px_minmax(0,1fr)_260px]">
  <aside className="space-y-5"><div className="h-card p-5"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-full bg-indigo-100 font-bold text-indigo-700">{name[0]}</div><div><h2 className="font-bold text-slate-900">{user?.full_name||"Gnanendhra"}</h2><p className="text-xs text-slate-500">Aspiring AI Engineer</p></div></div><p className="mt-4 flex items-center gap-1 text-xs text-slate-500"><MapPin size={13}/> Bengaluru, India</p><div className="mt-5 space-y-3 border-t border-slate-100 pt-4"><div><div className="mb-1 flex justify-between text-xs font-semibold text-slate-600"><span>Profile completion</span><span>82%</span></div><div className="progress-track"><span style={{width:"82%"}}/></div></div><div className="flex items-center justify-between rounded-lg bg-violet-50 px-3 py-2 text-xs"><span className="text-violet-700">AI profile score</span><strong className="text-violet-800">82 / 100</strong></div></div><Link href="/candidate/profile" className="mt-4 flex items-center justify-center gap-1 text-xs font-bold text-indigo-600">Improve profile <ChevronRight size={14}/></Link></div><div className="h-card p-5"><p className="text-xs font-bold uppercase tracking-wide text-slate-400">Your momentum</p><div className="mt-4 flex items-end gap-2"><strong className="text-3xl text-slate-900">+18%</strong><span className="mb-1 text-xs text-emerald-600">this week</span></div><p className="mt-2 text-xs leading-5 text-slate-500">You are appearing in more searches after adding your RAG project.</p></div></aside>
  <main className="space-y-5"><div className="flex items-center justify-between"><div><h2 className="font-bold text-slate-900">Top matches for you</h2><p className="mt-1 text-xs text-slate-500">Clear match reasoning, before you apply.</p></div><Link href="/jobs" className="text-xs font-bold text-indigo-600">See all</Link></div>{recommendations.map(job=><article key={job.id} className="h-card p-5 transition-shadow hover:shadow-md"><div className="flex gap-4"><div className={`grid h-11 w-11 shrink-0 place-items-center rounded-lg font-bold ${job.tone}`}>{job.company[0]}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-bold text-slate-900">{job.title}</h3><p className="mt-1 text-sm text-slate-600">{job.company} <span className="text-slate-300">·</span> {job.location}</p></div><div className="text-right"><strong className="text-lg text-emerald-600">{job.match}%</strong><p className="text-[10px] font-bold uppercase text-slate-400">AI match</p></div></div><div className="mt-4 flex flex-wrap gap-2">{job.skills.map(s=><span key={s} className="h-chip good"><Check size={12}/>{s}</span>)}<span className="h-chip bg-amber-50 text-amber-700">Missing: {job.gap}</span></div><div className="mt-5 flex items-center justify-between"><span className="text-xs text-slate-500">{job.salary} · Posted 2d ago</span><div className="flex gap-2"><Link href={`/jobs/${job.id}`} className="h-btn h-btn-secondary">View job</Link><Link href={`/jobs/${job.id}`} className="h-btn"><Sparkles size={14}/> Apply with AI</Link></div></div></div></div></article>)}</main>
  <aside className="space-y-5"><div className="h-card p-5"><div className="flex items-center gap-2"><TrendingUp size={17} className="text-indigo-600"/><h2 className="font-bold text-slate-900">Trending roles</h2></div><div className="mt-4 space-y-3">{trends.map((t,i)=><Link href="/jobs" key={t} className="flex items-center justify-between text-sm text-slate-700 hover:text-indigo-600"><span><em className="mr-2 not-italic text-slate-400">0{i+1}</em>{t}</span><ChevronRight size={15}/></Link>)}</div></div><div className="h-card p-5"><p className="text-xs font-bold uppercase tracking-wide text-slate-400">Career insight</p><h3 className="mt-3 font-bold text-slate-900">You are close to your next role.</h3><p className="mt-2 text-sm leading-5 text-slate-600">Cloud fundamentals are the only recurring skill gap in your strongest matches.</p><Link href="/career" className="mt-4 inline-flex items-center gap-1 text-xs font-bold text-indigo-600">Explore your plan <ArrowRight size={13}/></Link></div></aside>
 </div></div> }
